<h1>A 404 error occurred</h1>
<h2><?= $this->message ?></h2>

<?php if (isset($this->reason) && $this->reason): ?>

    <?php
    $reasonMessage = '';
    switch ($this->reason) {
        case 'error-controller-cannot-dispatch':
            $reasonMessage = 'O controlador solicitado não foi capaz de despachar o pedido.';
            break;
        case 'error-controller-not-found':
            $reasonMessage = 'O controlador solicitado não pôde ser mapeado para uma classe de controlador existente.';
            break;
        case 'error-controller-invalid':
            $reasonMessage = 'O controlador solicitado não foi despachável.';
            break;
        case 'error-router-no-match':
            $reasonMessage = 'O URL solicitado não pode ser correspondido por roteamento.';
            break;
        default:
            $reasonMessage = 'Não podemos determinar neste momento porque um 404 foi gerado.';
            break;
    }
    ?>

    <p><?= $reasonMessage ?></p>

<?php endif ?>

<?php if (isset($this->controller) && $this->controller): ?>

    <dl>
        <dt>Controlador:</dt>
        <dd><?= $this->escapeHtml($this->controller) ?>
            <?php
            if (isset($this->controller_class)
                && $this->controller_class
                && $this->controller_class != $this->controller
            ) {
                echo '(' . sprintf('resolve para %s', $this->escapeHtml($this->controller_class)) . ')';
            }
            ?>
        </dd>
    </dl>

<?php endif ?>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

    <?php if (isset($this->exception) && ($this->exception instanceof Exception || $this->exception instanceof Error)): ?>
        <hr/>
        <h2>Additional information:</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->exception->getMessage() ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre class="prettyprint linenums"><?= $this->exception->getTraceAsString() ?></pre>
            </dd>
        </dl>
        <?php
        $e = $this->exception->getPrevious();
        $icount = 0;
        if ($e) :
            ?>
            <hr/>
            <h2>Previous exceptions:</h2>
            <ul class="unstyled">
                <?php while ($e) : ?>
                    <li>
                        <h3><?= get_class($e) ?></h3>
                        <dl>
                            <dt>Arquivo:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getFile() ?>:<?= $e->getLine() ?></pre>
                            </dd>
                            <dt>Mensagem:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getMessage() ?></pre>
                            </dd>
                            <dt>Rastreamento de pilha:</dt>
                            <dd>
                                <pre class="prettyprint linenums"><?= $e->getTraceAsString() ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php
                    $e = $e->getPrevious();
                    $icount += 1;
                    if ($icount >= 50) {
                        echo "<li>Pode haver mais exceções, mas não temos memória suficiente para processá-lo.</li>";
                        break;
                    }
                endwhile;
                ?>
            </ul>
        <?php endif; ?>

    <?php else: ?>

        <h3>Mais nenhuma exceção disponível</h3>

    <?php endif ?>

<?php endif ?>
