<?php
$this->headTitle('Mudar senha');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Gerenciar Usuário' => $this->url('users'),
    'Alterar Senha' => $this->url('users', ['action' => 'change-password', 'id' => $user->getId()])
]);

$form->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite a senha antiga'
]);

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Insira a nova senha'
]);

$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-introduza a nova palavra-passe'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<h1>Alterar senha para <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   


