<?php
$this->headTitle('Editar Sala');

$this->mainMenu()->setActiveItemId('Rooms');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Gerenciar Salas' => $this->url('rooms'),
    'Editar Sala' => $this->url('rooms', ['action' => 'editroom', 'id' => $room->getId()])
]);

$form->get('room_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Sala 1'
]);

$form->get('area')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Área da Sala'
]);

$form->get('status')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Savar');

$form->prepare();
?>

<h1>Editar Sala <?= $this->escapeHtml($room->getRoomName()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('room_name')); ?>
            <?= $this->formElement($form->get('room_name')); ?>
            <?= $this->formElementErrors($form->get('room_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('area')); ?>
            <?= $this->formElement($form->get('area')); ?>
            <?= $this->formElementErrors($form->get('area')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   

