<?php
$this->headTitle('Editar usuário');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Gerenciar Usuário' => $this->url('users'),
    'Editar Usuário' => $this->url('users', ['action' => 'edit', 'id' => $user->getId()])
]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'nome@exemplo.com.br'
]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Nome Completo'
]);

$form->get('status')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Savar');

$form->prepare();
?>

<h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   

