<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Salas' => $this->url('rooms'),]);
?>

<h1>Gerenciar Salas</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('rooms', ['action' => 'addroom']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nova Sala
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>IDSala</th>
        <th>Nome da Sala</th>
        <th>Area</th>
        <th>Data de Criação</th>
        <th>Status</th>
        <th>Ações</th>
    </tr>

    <?php foreach ($rooms as $room): ?>

        <tr>
            <td><?= $this->escapeHtml($room->getId()); ?></td>
            <td>
                <a href="<?= $this->url('rooms', ['action' => 'viewroom', 'id' => $room->getId()]); ?>">
                     <?= $this->escapeHtml($room->getRoomName()); ?>
                </a>
            <td>
                <?= $this->escapeHtml($room->getArea()); ?>

            </td>
            </td>
            <td><?= $this->escapeHtml($room->getDateCreated()); ?></td>
            <td><?= $this->escapeHtml($room->getStatusAsString()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('rooms',
                    ['action' => 'editroom', 'id' => $room->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil"></span> Editar
                </a>
                <a class="btn btn-info" href="<?= $this->url('rooms',
                    ['action' => 'deleteroom', 'id' => $room->getId()]); ?>">
                    <span class="glyphicon glyphicon-erase"></span> Excluir
                </a>
                <a class="btn btn-info" href="<?= $this->url('rooms',
                    ['action' => 'scheduleroom', 'id' => $room->getId()]); ?>">
                    <span class="glyphicon glyphicon-calendar"></span> Reservar
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

<?= $this->paginationControl($rooms,
    'Sliding',
    'user/partial/paginator',
    array('route' => 'rooms')); ?>


