<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Gerenciar Usuário' => $this->url('users'),]);
?>

<h1>Gerenciar Usuários</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('users', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Novo Usuário
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>E-mail</th>
        <th>Nome Completo</th>
        <th>Data de Criação</th>
        <th>Status</th>
        <th>Ações</th>
    </tr>

    <?php foreach ($users as $user): ?>

        <tr>
            <td><?= $this->escapeHtml($user->getId()); ?></td>
            <td>
                <a href="<?= $this->url('users', ['action' => 'view', 'id' => $user->getId()]); ?>">
                    <?= $this->escapeHtml($user->getEmail()); ?>
                </a>
            </td>
            <td><?= $this->escapeHtml($user->getFullName()); ?></a>
            </td>
            <td><?= $this->escapeHtml($user->getDateCreated()); ?></td>
            <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('users',
                    ['action' => 'edit', 'id' => $user->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil"></span> Editar
                </a>
                <a class="btn btn-default" href="<?= $this->url('users',
                    ['action' => 'change-password', 'id' => $user->getId()]); ?>">
                    <span class="glyphicon glyphicon-asterisk"></span> Mudar Senha
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

<?= $this->paginationControl($users,
    'Sliding',
    'user/partial/paginator',
    array('route' => 'users')); ?>


