<?php
$this->headTitle('Ver Usuário');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Gerenciar Usuário' => $this->url('users'),
    'Ver Usuário' => $this->url('users', ['action' => 'view', 'id' => $user->getId()])
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Visualizar Usuário</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td>
                <?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td>
                <?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Nome Completo:</th>
                <td>
                <?= $this->escapeHtml($user->getFullName()) ?></th>
            </tr>
            <tr>
                <th>Data de Criação:</th>
                <td>
                <?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td>
                <?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>