<?php
$this->headTitle('Ver Sala');

$this->mainMenu()->setActiveItemId('rooms');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home'),
    'Gerenciar Salas' => $this->url('rooms'),
    'Ver Sala' => $this->url('rooms', ['action' => 'viewsala', 'id' => $room->getId()])
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>Visualizar Salas</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td>
                <?= $this->escapeHtml($room->getId()) ?></th>
            </tr>
            <tr>
                <th>Nome da Sala:</th>
                <td>
                <?= $this->escapeHtml($room->getRoomName()) ?></th>
            </tr>
            <tr>
                <th>Area da Sala:</th>
                <td>
                <?= $this->escapeHtml($room->getAreA()) ?></th>
            </tr>
            <tr>
                <th>Data de Criação:</th>
                <td>
                <?= $this->escapeHtml($room->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td>
                <?= $this->escapeHtml($room->getStatusAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>