<?php
$this->headTitle('Bem Vindo');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
    'Início' => $this->url('home')
]);
?>

<h1>Bem vindo</h1>

<p>
    Este é o aplicativo Challenges-app foi desenvolvido por Marcelo Silveira. Ele demonstra
    como implementar a autenticação do usuário e como restringir certas páginas a serem
    acessado por usuários não autorizados, incluindo uma sessão de reserva de salas.
</p>

<p>
    Cliquem no botão <em>Login</em> no canto superior direito. Para entrar, usando as
    seguintes credenciais:
<ul>
    <li>Usuário: <em>admin@example.com</em></li>
    <li>Senha: <em>Secur1ty</em></li>
    <li>Conforme descrito na criação do banco de dados</li>
    <li>O Usuário <em>admin@example.com</em> será criado automáticamente após a execução</br>de <em>php ./vendor/bin/doctrine-module migrations:migrate</em></li>
</ul>
</p>



